services:
  freshrss-app:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    volumes:
      - freshrss_data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - homelab_network
      - default
    ports:
      - 8082:80
networks:
  homelab_network:
    external: true
  default:
    driver: bridge
volumes:
  freshrss_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/docker/volumes/freshrss/_data
