services:
  seatable:
    image: seatable/seatable-developer:latest
    container_name: seatable
    ports:
      - "8096:80"  # Ändern Sie dies, wenn Port 80 bereits verwendet wird
      - "6443:443" # Ändern Sie dies, wenn Port 443 bereits verwendet wird
    volumes:
      - /opt/seatable/data:/shared   # Pfad zum Datenverzeichnis (anpassen)
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWORD=${DB_PASSWORD} # Sicheres Root-Passwort für MariaDB
      - SEATABLE_SERVER_HOSTNAME=${DOMAIN}  # Ihre Domain (ohne http/https)
      - SEATABLE_SERVER_SCHEME=http # Ändern Sie dies in "http", wenn Sie kein HTTPS verwenden
      - SEATABLE_ADMIN_EMAIL=${ADMIN_EMAIL}   # Admin-E-Mail-Adresse
      - SEATABLE_ADMIN_PASSWORD=${ADMIN_PASSWORD}  # Admin-Passwort
    depends_on:
      - db
    networks:
      - seatable-net

  db:
    image: mariadb:10.11
    container_name: seatable-db
    volumes:
      - /opt/seatable/db-data:/var/lib/mysql  # Pfad zum DB-Datenverzeichnis (anpassen)
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Sicheres Root-Passwort für MariaDB
    networks:
      - seatable-net

networks:
  seatable-net:
