services:
  db:
    container_name: baserow_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER:-baserow}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?}
      - POSTGRES_DB=${DATABASE_NAME:-baserow}
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - stack.env
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/docker/volumes/baserow/db:/var/lib/postgresql/data/pgdata

  baserow:
    depends_on:
      - db
    container_name: baserow
    image: baserow/baserow:latest
    environment:
      BASEROW_PUBLIC_URL: "http://192.168.178.35"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME:-baserow}
      DATABASE_USER: ${DATABASE_USER:-baserow}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
    ports:
      - "5685:80"
      - "443:443"
    volumes:
      - /var/lib/docker/volumes/baserow/data:/baserow/data
    env_file:
      - stack.env
