name: Test Docker Compose

on: [push]

jobs:
  test-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Docker Compose testen
        run: |
          docker compose -f compose-files/common-networks.yml config
          for dir in compose-files/applications/*/docker-compose.yml ; do
              if [ -f "$dir" ]; then
                  docker compose -f "$dir" config
              fi
          done
