name: Test Docker Compose
on: [push]

jobs:
  test-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Docker Compose testen
        run: |
          docker compose -f compose-files/common-networks.yml config
          for dir in compose-files/applications/*/ ; do
              docker compose -f "$dir/docker-compose.yml" config
          done
