name: Lint YAML files
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - "compose-files/**"

jobs:
  yaml:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          yamllint_flags: '-c .github/yamllint.config.yml .'
